sources:
  - name: taco-ethereum
    handler:
      graphql:
        endpoint: ${VITE_SUBGRAPH_ETHEREUM}
    transforms:
      - autoPagination:
          limitOfRecords: 2000
  - name: taco-polygon
    handler:
      graphql:
        endpoint: ${VITE_SUBGRAPH_POLYGON}
    transforms:
      - autoPagination:
          limitOfRecords: 2000
  - name: taco-base
    handler:
      graphql:
        endpoint: ${VITE_SUBGRAPH_BASE}
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql
